language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: YDayGEfnoELnTgOMd3Ruvb005Nbg3A70A8u5uBZhx57+0Q8duStq1Yfsu/Q6agO6wmoKTqkSN6fwFAOdxruGW6ey5sCK8hI1IRA58PZJ81gOpOEUxKlOgWlzHfiGKYoYOqdwIJKwCJQVDYmESrpKDocaYCULNkC8T1htK+ZyQ2afgkNFwU00qiVQu3ML90KJVBwj3H+gN0s5JzNgpjnQBHiLyUQd4A34Ty/9ojPSBtfzjqqVC6aJKlxy5MGDLyQ/RxbCJu0CEQz3Mlxi3mDN4Rtq4u/0kJE/uk82rVHEab/vmIM4lNxrw/3/UfyN5XCSe9YOotVVAAB+JKxJWvreE3Cbc8mf2C126rqpPN/m82HOyAYrebpfls2KuCDIVbzqeG2xRCmBBSbr8Dt7nauILrmI79E1wyOLTiV+8WW1K6DwFTHv2Iq70IrbU0iQsJ7IsAsEKIKANPMmbIng+BF2Q7ymKHW+ZS1NaAsLeAYVsrw7UNPlbJIjKEXQbwtfVed8LAr6kLOxnwMvyPQqTSDoeUwei4OvU20jTvCwd+bbUfzCdPyJHW6hQoE7OiOX8px1iq2vuWHmeYCRL8kILckMyX+t4YxgRgsm8YZIGIRKj/ERtrQkTegXoebJwfimdKXaLW4M3DZi/rmcfbQcSgc7nL1fnqanYkAhgNyo6YYCuBs=
  app: rd-hisdt
