language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: DiElCoKqgmRJJ7xilTCLyazMW5111suSPgDvzh3kRvaJUEdVA3J92Rc8tCCcag7dNzX1exYC+37yn8sPk5/5GwOsyGNr8C9fqI5to6sP6wmo6DYVpxk3wFs/XilKn/icMs7IELJgdaX4I0RjAKeXgsYyYaV3CET+dLKnqadRzNwDwTbQmShaaz3tfY3araxli1jFsqu/QYk4N1x6GcgKJFKUcOHqSXHzi6QiGZXS6ikZ5pIm58fQOFkG5oB5j1wPvtmALTvv2vpkiJcGpfpN3PcpRSlPmLsKHY3jIPi3XXhnpbmtXIRYwrwvQXzrsqGVVepqW8bYGErQ0VA0myutWhpajX67yNqBuXiaPUn3001xWwvDsQC9vPCGHN2FUPzMYIJy0jtkHsdbGIJNLpFfkXlLJ6PMCYfOkMh4zSx4LGX3PzBs8Tu4d57TeTRHXrWDu37YoS3cIr+wTDO5LJbrfdxc79JiTChll7z7emnsXkR6FgeKVNIBhjtuGAjDAZCDO2ajVRJx6RkmyzcXxxSZ2/E7/LEIWP7bJgv4b29pz3t+mkr+Pt9XHxOl+4ZnxYbg/m4dvRP3Y4erNxifufYYEdDWBTg972AMYrrUq5mVr6sacOk3GPJONWXjSiIeFmo9QxcRd4IkL1Q80SsK96awgUlCuqAk3yXBWWDagvh4erQ=
  app: rd-hisdt